import {ACTION_ENTRY_PHASE_POLICY} from "../../shared/source-transition-policy.js";
import { CONVERSATIONAL_REACH_POLICY } from "../../shared/conversational-reach-policy.js";
/** Shared by the factual-scaffold rewriter and its content reviewer. */
export const sceneActionPolicy = [
  ACTION_ENTRY_PHASE_POLICY,
  'Authorization is about meaningful actions and state changes, not a literal whitelist of every verb. Allow incidental physical details that realize an authorized action without changing its actor, goal, causal order, outcome or required state (for example, standing before running, or stepping closer to bite). This applies to automatic NPC actions as well as selected player actions.',
  'Incidental detail never authorizes a new decision, command, commitment, destination, transfer, successful completion of an attempt, recovery from a required limitation, or any part of nextDecision. A detail that crosses one of those boundaries is a material extra action and must fail authorization, even if the ending otherwise matches. Do not reject harmless connective movement solely because its verb is absent from the index.',
  'Viewpoint does not change ownership: actor is the person performing every verb in that beat, including the first verb. I/me/my refer only to the viewpoint character, never automatically to the actor of the current beat. Keep other actors named or use unambiguous third-person pronouns. Do not transfer waking, seeing, speaking or movement to the narrator to introduce a first-person scene. Source context does not establish that the narrator personally witnessed events elsewhere; do not invent witnessing, memories or a report to bridge that gap.',
].join('\n');

/** Continuous prose may establish context later without performing actions later. */
export const sceneStatePolicy = [
  CONVERSATIONAL_REACH_POLICY,
  'TEMPORAL PARTICIPANT STATE: maintain each named participant’s location separately at every point in the prose, not only at the ending. In serial crossings, a passenger remains on the departure bank until their own crossing. A phrase such as waiting with A and B asserts co-location at that moment; never import those people from a later crossing or a final group snapshot. Compare each such assertion with preceding authorized transitions. A correct later crossing or final sceneScope does not repair an earlier premature arrival. Reject the premature assertion as an order/state contradiction; do not invent an extra crossing to reconcile it.', 
  'Assess the meaning of resulting states, not word-for-word restatement. When an action stops an earlier activity, clearly stopping that same work establishes cessation without repeating its historical subtype. A specific earlier task need not be named again unless its identity affects a required present fact or action. This does not allow replacing a required specific operation or object with generic work, omitting an action, claiming completion from an attempt, or contradicting the indexed facts.',
  'Distinguish when a fact is stated from when an action happens. An unchanged background state (such as where someone is standing) may be established later in the continuous scene and support an earlier checkpoint when the prose presents it as ongoing and no intervening transition or contradiction changes it. Do not require that context to be restated after every beat. An explicit later arrival, acquisition, recovery or other state change cannot be projected backward; a final state alone never proves an earlier required action occurred. Explain uncertainty only when the actual text leaves a material state unresolved, not merely because its description is in a later sentence.',
  'sceneScope describes the actual ending, not the cast mentioned throughout the scene. peoplePresent means physically at the player’s current location; peopleWithinSpeakingDistance means established nearby conversational reach. Someone who explicitly leaves that location may remain visible or mentioned while correctly absent from peoplePresent. Do not require their inclusion merely because the narrator describes them moving away. Do not infer conversational reach from an earlier call before departure. Silent arrivals, omitted people who remain physically present, and genuinely unsupported scope claims still fail.',
  'The legacy name peoplePresent includes living animal and nonhuman characters, not just humans. A character whose hiding place is known within the current room remains present even when not visible, unable to speak, or beyond immediate physical reach. Do not equate presence with being touchable or verbal. Never omit such a character from metadata solely for those reasons; presence does not authorize speech or remove a physical obstacle.',
  'Established proximity persists until the prose shows movement, departure, a barrier, or another relevant change. When two characters meet at a doorway and one directly addresses the other, a later statement that one remains in the house does not by itself move that character elsewhere or cancel speaking distance. Do not invent separation or require the same proximity to be independently restated at the ending. Shared building alone, without established proximity, is not enough.',
].join('\n');

