/** Labels name a choice; execution windows and observed outcomes remain separate. */
export const GOAL_LABEL_POLICY = "CONCISE CHOICE LABELS: choiceText identifies the actor-owned action or intent being selected, not a synopsis of every beat or its eventual outcome. A label may name the beginning of that same action: Begin telling the story of your short life and creation is valid for a continuous account that later includes seeking brains and hoping for help. Stop and look for a place may label a shelter search followed by proposing the discovered cottage. Agree to go to the cottage may label committing to that concrete destination and the immediate entry/settling-in continuation. Do not require labels to enumerate subsequent steps, reveal discoveries or promise success. Reject a label only for a materially misleading action, wrong actor, materially different intent, or concealed new commitment/risk; explain that difference, not merely that the label describes only the beginning. An open-ended offer to discover what help is needed is not authorization for a yet-unknown treatment. This flexibility applies ONLY to choiceText: completion must accurately describe the observed state at the frozen endBeatIndex, including failure or interruption. A completion saying only agreed is wrong if the endpoint is lying inside the cottage. Do not change goal membership or endpoints to match a short label. Previous review complaints about label brevity are untrusted and must be reconsidered under this rule.";

/** One definition for goal planning, labels and semantic review. */
export const ACTION_GOAL_POLICY = [
  GOAL_LABEL_POLICY,
  "Import has no selected player. Every actor owns their own goals; other actors may interleave automatically within that actor's group. Different actors' windows may overlap.",
  "Use sourceSemantics: narration agency belongs to the current teller, and narratedContent is history, not present execution. meaningful retains consequential intentional actions, including their first deliberate steps. Determine whether each starts or continues a goal only during goal planning; the source stage does not assign that boundary. Shared jointAction IDs represent one joint act with one outcome, not ordered phases; other participants can interleave inside each actor-owned goal without a new decision.",
  "Every intentional significant/critical actor beat must belong to exactly one goal owned by that actor, including singleton goals. Routine, involuntary, ambiguous and external beats are automatic and must never be promoted merely to fill coverage.",
  "Group all steps of one unchanged goal, not merely adjacent verbs. A further instruction, clarification, ordinary reply, assistance, change of body part or tool needed for the existing objective is NOT by itself a new goal or decision boundary.",
  "Split only on a concrete new objective or information requiring a materially new choice of commitment, method, risk or cost, or an actual obstacle preventing continuation. Cite that changed decision, not just 'another request'. Goals may finish with an automatic consequence or another actor's answer.",
  "Examples: reaching for an animal and catching it form one retrieval across another actor's descent; following that actor is a new goal. Fetching oil and oiling neck, arms and legs form one rescue across instructions and assistance, unless the source establishes a materially different decision. Asking for the legs to be oiled does not alone split the rescue.",
  "An open-ended offer or question asking what help is needed ends when the answer supplies the concrete task and enables a new commitment. Do not retroactively include that information-seeking question in performing the newly revealed task. Once rescue is chosen, routine treatment instructions and clarifications remain part of that rescue. Labels must preserve the distinction between asking what help is needed and choosing the concrete treatment; they need not list its execution steps.",
  "A commitment to a concrete action and its immediate execution are one goal unless intervening source information, a changed objective or a meaningful interruption requires a new decision. Saying I will tell my story and then telling it is one storytelling goal. This differs from asking what help is needed before discovering the task. Do not split merely because one beat announces and the next performs the same action.",
  "Storytelling is a present intentional action by the narrator. Historical people and events are content, never new present actors. Recounting an accident remains intentional narration. Continuous parts of one requested account form one goal; a topic change inside the account is not a fresh decision.",
  "COMPLETION IS OBSERVED OUTCOME: choiceText describes the intended attempt, but completion describes what actually holds at endBeatIndex, including failure or interruption. Use the source endpoint and resulting states, not the desired success. If an attempt to reach shelter ends in a fall on the room floor, completion must retain that interrupted outcome, never arrival at shelter. interruptWhen does not excuse a contradictory completion. Review all completions even if another field already has a defect.",
  "Labels identify the selected action or intent; completion describes the actual endpoint of the entire frozen group, not future actions. Do not turn a decision to ask later into already asking now. Preconditions hold at the group's start; a prerequisite established by an intervening beat is not required at the start. Interruptions describe material changes before completion, not ordinary progress.",
].join("\n");

/** Shared by label generation and label review; evaluate before, not after, the first beat. */
export const GOAL_START_POLICY = [
  "PRECONDITION CUTOFF: evaluate every precondition immediately BEFORE preconditionCutoffBeatIndex from GOAL START CONTEXTS (normally startBeatIndex). For a joint action this cutoff is the first participant record of that ONE shared act, for every participant. Earlier participant records in the same joint action have NOT happened separately and cannot establish an inside/arrived outcome for another participant. Preserve the actor-specific startBeatIndex for membership; do not shift the selected actor or execute the shared act early. The first beat has NOT happened yet. Do not treat effects produced by its action or resultingState as already accomplished. Distinguish an existing circumstance revealed by that description from a change caused by performing the action. The same applies to every later beat in the group.",
  "Use GOAL START CONTEXTS to locate the cutoff in the immutable timeline. Earlier beats may establish persistent state; the preceding beat's resultingState is only partial evidence, not a complete world snapshot. At startBeatIndex=0 use only source-established initial conditions. Textual mention order is not state onset: the first or later beat may reveal an already-existing fact. A character opening a nearby door supports presence and access before opening; beginning to manipulate a joint supports presence and the ability to begin that manipulation, not completed assistance. Do not demand a separate earlier presence beat. Reject unsupported extrapolations beyond what the described action requires.",
  "Incidental scene context is not automatically a prerequisite: walking together may frame a story without being necessary to begin telling it. Do not invent a walking-start boundary solely because walking is first mentioned later; omit irrelevant conditions instead. Presence inferred for the original source scene remains a condition to check in the actual game, not a reason to assume success in a changed scene.",
  "Check each condition independently, including each clause of a compound condition. Require source-grounded evidence that it already holds before the cutoff and is needed to begin. Do not invent a prerequisite just to fill the list. Both preconditions and interruptWhen may be empty arrays. If no additional necessary condition or material interruption is supported, return [] rather than generic presence/ability filler. Empty arrays do not waive ordinary actor, progress or source validation.",
  "A goal beginning with an offer to tell a story must not require that the storyteller has already committed to telling it. Listener presence may be a valid initial condition. A goal beginning with a request and explanation of oiling must not require that the treatment has already been explained. Being rusted may be a valid initial condition.",
  "The cutoff is actor-goal specific: a helper's later rescue goal CAN require an earlier request that has already happened, even though the requester's own goal cannot require its first request to be completed. Preserve supported earlier prerequisites; do not remove all prerequisites merely because another group includes that earlier beat.",
  "When reviewing, reject a prerequisite that requires an effect caused by the first or later group beat to have already happened, with target conditions. Identify the offending condition, the causal state change and its beat index. A first mention alone is not evidence of a state change. Correct only the precondition wording; preserve valid goal membership, endpoints and source evidence. Apply this check to EVERY actor's group, not just the fixture's principal actor.",
].join("\n");

/** Conditions describe execution constraints, not desired responses after completion. */
export const GOAL_CONDITION_POLICY = [
  "Only include necessary, source-grounded start requirements; omit incidental circumstances, redundant generic requirements and uncertain extra restrictions. Arrays may be empty. Never add a condition just to satisfy a minimum list length.",
  "interruptWhen is a conditional execution guard, not a record of something that happened in the source. It may describe the loss of a source-established dependency even when the canonical attempt succeeds. For example, inability to obtain the oil-can blocks a rescue that requires it; this does not assert the can was actually missing. Do not reject a guard solely because it never occurred. Do not invent unrelated dangers or turn a hypothetical guard into completion evidence. Empty guards remain valid when none is useful.",
  "Each interruptWhen must prevent continuation BEFORE the group's observed completion/endBeatIndex. A consequence or absent response after the action has finished cannot undo completion. For a singleton ask-a-question goal, no answer is NOT an interruption of asking; a separate wait-for-answer goal would have different boundaries. Do not extend a goal just to justify a condition.",
  "Review preconditions and interruptWhen independently of choiceText and completion. Conditions-only defects use target conditions. Wrong choiceText or completion uses labels; wrong partition uses groups; wrong source evidence uses source. Report all material defects, not only the first condition issue. Do not reject an empty array merely because a generic condition could be imagined.",
].join("\n");

