/** Shared by index generation, structural repair and semantic group review. */
export const PLAYER_ACTION_ACTOR_POLICY = "ACTOR-NEUTRAL BOOK INDEX: no player character has been selected during import. Build and review intentional meaningful action groups for EVERY actor, not only the protagonist. For each group, its first beat's actor is the hypothetical player; other actors are automatic/NPC participants only relative to that group. The same character can own a playerAction in their own group and be an automatic participant in another actor's group. Never remove or reject a group merely because its actor is a supporting character, an animal, or an NPC when playing someone else. Dialogue, proposals, instructions and movement by those actors remain eligible when intentional and meaningful. Actual player selection and capability checks happen at runtime. This does not authorize routine/involuntary beats as player actions or permit crossing real decision boundaries.";

/** Optional annotations must obey the same eligibility and scope in every import stage. */
export const PLAYER_ACTION_GROUP_POLICY = [
  "GROUP ELIGIBILITY: only actor-owned intentional significant/critical beats may start or be listed in a playerAction. Routine, involuntary, external and ambiguous beats remain automatic; never demand a group on them or promote their stakes merely to obtain a group.",
  "GROUP COVERAGE: playerAction is optional. A null annotation alone is not a review defect, including on an eligible singleton or uncertain goal. Do reject an existing group that omits part of its own clearly source-backed unchanged goal. Never solve a rejected group by deleting it merely to avoid review.",
  "GROUP OWNERSHIP: an event has no hypothetical player. Each annotated start defines its OWN hypothetical player, even inside another actor's group window. A separate group owned by actor B is legal inside actor A's window; it is automatic only when executing A's group, not globally. Only playerBeatIndexes must belong to the owning actor.",
  "GROUP COMPLETION: completion and boundaryReason describe the source-backed endpoint. interruptWhen describes a concrete obstacle or changed decision requiring new input BEFORE completion, not successful completion, an ordinary reply or NPC interleaving. Do not invent an interruption in the source.",
  "GROUP BINDING: derive each label and completion from the explicitly indexed owning beat and its actual window. After inserting or splitting beats, recompute all affected annotations; never carry labels forward by old array position.",
].join("\n");
