/** Conditions of choosing a goal are distinct from conditions of its later steps. */
export const ACTION_ENTRY_PHASE_POLICY = [
  'ACTION ENTRY PHASES: playerAction.preconditions describe what must already hold BEFORE choosing and beginning the bounded goal. They must not demand that a preparatory step inside that chosen goal has already happened. Distinguish choosing/committing, authorized preparation, and execution/completion. A condition needed immediately before a later substep is not automatically a prerequisite of the whole choice.',
  'For an indexed carrying/crossing goal, source-backed commitment to try, inviting an available companion aboard, boarding, and then crossing may be successive parts of executing that same goal. The passenger must be aboard before the jump, but need not be aboard before the player chooses the carrying goal. Preserve who boards and on which side, and show boarding before transport; do not teleport passengers. Do not move the action start past the player’s commitment or invitation just to make a mounted-passenger condition true.',
  'Keep real entry constraints: an available passenger/vehicle, source-supported cooperation, accessible starting positions, required capabilities and no established blocking obstacle. Do not assume another actor’s consent, an absent passenger’s arrival, an unlocked gate, acquisition of a missing tool, or a separate meaningful decision. A player-controlled boarding or invitation decision must remain unperformed before selection. Preparation belongs inside the goal only when supported by the source and existing action boundaries; a distinct choice or actual interruption still requires its own boundary.',
  'Repair a phase error in preconditions when the existing source-backed goal already includes the preparation: replace the prematurely completed state with the necessary supported entry conditions. Preserve action ordering and physical safety at execution time. If the source beat or group excludes necessary steps, report a source/group boundary issue instead of silently widening the goal or deleting the real requirement.',
].join('\n');

/** Source extraction and rendering agree about physical transitions and decision boundaries. */
export const SOURCE_TRANSITION_POLICY = [
  ACTION_ENTRY_PHASE_POLICY,
  'TRANSPORT BOUNDARIES: when a vehicle, building or group moves, resultingState must preserve who traveled and who remains at the departure location. A concise description is sufficient when identities and separation are unambiguous from the source and prior state; do not require an exhaustive repeated roster. Evaluate positions at the end of this beat, before the next unperformed action. Do not advance a return journey or other future movement into the earlier checkpoint. Preserve source-backed separation, including location names when supplied. resultingState describes the final state, not a transcript of intermediate boarding or execution steps. A nearby room, cellar, platform or other fixed place does not move merely because it was previously beneath or beside the moving object. Do not infer additional passengers.',
  'AUTOMATIC BEFORE INTENTIONAL: split waking from sleep, regaining awareness, involuntary reactions and routine orientation from the subsequent deliberate investigation or commitment. Waking caused by a shock is involuntary; sitting up and noticing that motion has stopped can be routine. Neither should require selecting a future action such as opening a door. Preserve supporting actors as separate atomic beats and keep the source order.',
  'NARRATOR ACCESS: physical world state and character knowledge are different. Do not put unseen surroundings into a character\'s knowledge while asleep, unconscious or behind a closed door. Index the external change, awareness and later observation separately when the source does. Use narrow references; a later descriptive paragraph may establish a landing location but cannot authorize an earlier view of its scenery.',
];

